### PR TITLE
feat: update results ranking

### PR DESCRIPTION
**Pull request by houssemmimoun27**
This PR update the results ranking for nemeton builders program.

### CODE REVIEW

**Review by antho31 — APPROVED** [review]
Thanks! (Keep in mind **it should be published July 12, not before this date**)

**Review by ccamel — APPROVED** [review]
:+1:

**Comment by antho31** [comment]
When will it be updated today?

**Comment by fredericvilcot** [comment]
> When will it be updated today? 

@antho31 
There is only @amimart who can release and deploy , I asked him to release it ASAP..

**Pull request merged**
